const modal=document.getElementById('modal'), content=document.getElementById('modalContent'), toast=document.getElementById('toast');
const supabaseClient=window.supabase.createClient(window.OCCUPICK_SUPABASE_URL,window.OCCUPICK_SUPABASE_KEY);
let currentUser=null, currentProfile=null;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=(name='User')=>name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U';
function openModal(type){
 let html='';
 if(type==='signup') html=`<div class="auth-shell"><div class="auth-kicker">WELCOME TO OCCUPICK</div><h2>Create your account</h2><p class="auth-subtitle">Join a smoother way to find work or hire the right person.</p><form class="form auth-form" id="signupForm"><label>Full name<input id="signupName" required autocomplete="name" placeholder="Juan Dela Cruz"></label><label>Email<input id="signupEmail" required type="email" autocomplete="email" placeholder="you@example.com"></label><label>What are you here for?<select id="signupRole"><option value="worker">I'm looking for work</option><option value="client">I'm hiring</option></select></label><label>Password<div class="password-wrap"><input id="signupPassword" required minlength="6" type="password" autocomplete="new-password" placeholder="At least 6 characters"><button type="button" class="password-toggle" onclick="togglePassword('signupPassword',this)">Show</button></div></label><div class="password-meter"><span id="passwordMeter"></span></div><div class="auth-error" id="signupError" role="alert"></div><button class="btn auth-submit" type="submit"><span>Create account</span><span class="btn-loader"></span></button></form><p class="auth-switch">Already have an account? <button type="button" class="text-btn" onclick="openModal('login')">Log in</button></p></div>`;
 if(type==='login') html=`<div class="auth-shell"><div class="auth-kicker">WELCOME BACK</div><h2>Log in to OccuPick</h2><p class="auth-subtitle">Pick up where you left off.</p><form class="form auth-form" id="loginForm"><label>Email<input id="loginEmail" required type="email" autocomplete="email" placeholder="you@example.com"></label><label>Password<div class="password-wrap"><input id="loginPassword" required type="password" autocomplete="current-password" placeholder="Your password"><button type="button" class="password-toggle" onclick="togglePassword('loginPassword',this)">Show</button></div></label><div class="auth-row"><span></span><button type="button" class="text-btn small" onclick="openModal('forgot')">Forgot password?</button></div><div class="auth-error" id="loginError" role="alert"></div><button class="btn auth-submit" type="submit"><span>Log in</span><span class="btn-loader"></span></button></form><p class="auth-switch">New to OccuPick? <button type="button" class="text-btn" onclick="openModal('signup')">Create an account</button></p></div>`;
 if(type==='forgot') html=`<div class="auth-shell"><div class="auth-icon">✉</div><h2>Reset your password</h2><p class="auth-subtitle">Enter your email and we'll send you a secure reset link.</p><form class="form auth-form" id="forgotForm"><label>Email<input id="forgotEmail" required type="email" placeholder="you@example.com"></label><div class="auth-error" id="forgotError" role="alert"></div><button class="btn auth-submit" type="submit"><span>Send reset link</span><span class="btn-loader"></span></button></form><p class="auth-switch"><button type="button" class="text-btn" onclick="openModal('login')">← Back to log in</button></p></div>`;
 if(type==='task') html=`<div class="auth-shell"><div class="auth-kicker">CLIENT WORKSPACE</div><h2>Post a task</h2><p class="auth-subtitle">Describe the work and let OccuPick find relevant prospects.</p><form class="form auth-form" id="taskForm"><label>Task title<input id="taskTitle" required maxlength="120" placeholder="Create a logo for my shop"></label><div class="two-col"><label>Work type<select id="taskType"><option value="digital">Digital</option><option value="physical">Physical</option></select></label><label>Budget (₱)<input id="taskBudget" required min="1" step="0.01" type="number" placeholder="800"></label></div><label>Description<textarea id="taskDescription" rows="5" required maxlength="3000" placeholder="What needs to be done? Include requirements and deadline."></textarea><div class="auth-error" id="taskError"></div><button class="btn auth-submit" type="submit"><span>Post task</span><span class="btn-loader"></span></button></form></div>`;
 if(type==='profile') html=profileEditorHtml();
 if(type==='account') html=accountHtml();
 if(type==='marketplace') html=`<div class="workspace"><div class="workspace-head"><div><div class="auth-kicker">OPPORTUNITIES</div><h2>Find work</h2><p class="auth-subtitle">Browse real tasks posted to OccuPick.</p></div><button class="btn ghost" onclick="openModal('profile')">My profile</button></div><div class="market-tools"><input id="taskSearch" placeholder="Search tasks…"><select id="taskFilter"><option value="all">All work</option><option value="digital">Digital</option><option value="physical">Physical</option></select></div><div id="taskList" class="task-list"><div class="empty-state">Loading opportunities…</div></div></div>`;
 content.innerHTML=html; modal.classList.remove('hidden'); requestAnimationFrame(()=>modal.classList.add('modal-open'));
 if(type==='signup'){signupForm.addEventListener('submit',handleSignup);signupPassword.addEventListener('input',updatePasswordMeter)}
 if(type==='login')loginForm.addEventListener('submit',handleLogin);
 if(type==='forgot')forgotForm.addEventListener('submit',handleForgotPassword);
 if(type==='task')taskForm.addEventListener('submit',handleTask);
 if(type==='profile')loadProfileForm();
 if(type==='account')renderAccountData();
 if(type==='marketplace')loadTasks();
}
function profileEditorHtml(){const p=currentProfile||{};return `<div class="workspace"><div class="profile-cover"><div class="profile-avatar-lg" id="profileAvatarPreview">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="Profile">`:esc(initials(p.full_name))}</div><div><div class="auth-kicker">YOUR PROFILE</div><h2>Customize your profile</h2><p class="auth-subtitle">Make it easy for the right people to understand what you do.</p></div></div><form class="form auth-form" id="profileForm"><div class="two-col"><label>Full name<input id="profileName" required maxlength="80"></label><label>Username<input id="profileUsername" maxlength="30" placeholder="yourname"></label></div><div class="two-col"><label>I'm here as<select id="profileRole"><option value="worker">Worker / Prospector</option><option value="client">Client / Hirer</option></select></label><label>Location<input id="profileLocation" maxlength="120" placeholder="Cebu City"></label></div><label>Profile photo URL<input id="profileAvatar" type="url" placeholder="https://…"></label><label>Bio<textarea id="profileBio" rows="4" maxlength="500" placeholder="Tell people about your skills, experience, or what you need."></textarea></label><label>Skills<input id="profileSkills" placeholder="Canva, Video Editing, HTML, Data Entry"></label><div class="profile-preview" id="profileLivePreview"></div><div class="auth-error" id="profileError"></div><button class="btn auth-submit" type="submit"><span>Save changes</span><span class="btn-loader"></span></button></form></div>`}
function accountHtml(){return `<div class="workspace"><div id="accountData" class="account-loading">Loading your account…</div></div>`}
function togglePassword(id,b){const i=document.getElementById(id);if(!i)return;i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'}
function updatePasswordMeter(e){const v=e.target.value,m=document.getElementById('passwordMeter');if(!m)return;let s=0;if(v.length>=6)s++;if(v.length>=10)s++;if(/[A-Z]/.test(v))s++;if(/[0-9]/.test(v))s++;if(/[^A-Za-z0-9]/.test(v))s++;m.style.width=`${s*20}%`}
function setAuthError(id,msg){const e=document.getElementById(id);if(e)e.textContent=msg||''}
function setLoading(b,on,label){if(!b)return;b.disabled=on;b.classList.toggle('loading',on);const s=b.querySelector('span:first-child');if(s)s.textContent=on?'Please wait…':label}
function closeModal(){modal.classList.remove('modal-open');setTimeout(()=>modal.classList.add('hidden'),180)}
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)}
document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');document.getElementById('themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾';localStorage.setItem('occ-theme',document.body.classList.contains('dark')?'dark':'light')};
if(localStorage.getItem('occ-theme')==='dark'){document.body.classList.add('dark');document.getElementById('themeBtn').textContent='☀'}
async function handleSignup(e){e.preventDefault();const name=signupName.value.trim(),email=signupEmail.value.trim(),password=signupPassword.value,role=signupRole.value,b=e.submitter;setAuthError('signupError','');setLoading(b,true,'Create account');try{const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:name,role}}});if(error)throw error;if(data.user)await ensureProfile(data.user,{full_name:name,role});if(data.session){await refreshAuth();closeModal();showToast('Welcome to OccuPick! 🎉');openModal('profile')}else{content.innerHTML=`<div class="success-state"><div class="success-check">✓</div><h2>Check your email</h2><p>We sent a confirmation link to <strong>${esc(email)}</strong>. Confirm it, then log in.</p><button class="btn" onclick="openModal('login')">Back to log in</button></div>`}}catch(err){setAuthError('signupError',friendlyAuthError(err))}finally{setLoading(b,false,'Create account')}}
async function handleLogin(e){e.preventDefault();const email=loginEmail.value.trim(),password=loginPassword.value,b=e.submitter;setAuthError('loginError','');setLoading(b,true,'Log in');try{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;currentUser=data.user;await refreshAuth();closeModal();showToast('Welcome back 👋')}catch(err){setAuthError('loginError',friendlyAuthError(err))}finally{setLoading(b,false,'Log in')}}
async function handleForgotPassword(e){e.preventDefault();const email=forgotEmail.value.trim(),b=e.submitter;setAuthError('forgotError','');setLoading(b,true,'Send reset link');try{const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+window.location.pathname});if(error)throw error;content.innerHTML=`<div class="success-state"><div class="success-check">✓</div><h2>Reset link sent</h2><p>If an account exists for <strong>${esc(email)}</strong>, you'll receive instructions shortly.</p><button class="btn" onclick="openModal('login')">Back to log in</button></div>`}catch(err){setAuthError('forgotError',friendlyAuthError(err))}finally{setLoading(b,false,'Send reset link')}}
function friendlyAuthError(err){const m=(err?.message||'').toLowerCase();if(m.includes('invalid login credentials'))return'That email or password is incorrect.';if(m.includes('user already registered'))return'An account with this email already exists. Try logging in.';if(m.includes('password'))return'Please use a password with at least 6 characters.';if(m.includes('email'))return'Please enter a valid email address.';if(m.includes('rate limit'))return'Too many attempts. Please wait a moment and try again.';return err?.message||'Something went wrong. Please try again.'}
async function signOut(){const {error}=await supabaseClient.auth.signOut();if(error){showToast(error.message);return}currentUser=null;currentProfile=null;closeModal();updateNav();showToast('Logged out.')}
async function ensureProfile(user,initial={}){const payload={id:user.id,full_name:initial.full_name??user.user_metadata?.full_name??'',role:initial.role??user.user_metadata?.role??'worker'};const {error}=await supabaseClient.from('profiles').upsert(payload,{onConflict:'id',ignoreDuplicates:true});if(error)console.warn('Profile setup:',error.message)}
async function refreshAuth(){const {data}=await supabaseClient.auth.getSession();currentUser=data.session?.user||null;if(currentUser){await ensureProfile(currentUser);const r=await supabaseClient.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();currentProfile=r.data||null}updateNav()}
async function loadProfileForm(){if(!currentUser)return;await refreshAuth();const p=currentProfile||{};profileName.value=p.full_name||'';profileUsername.value=p.username||'';profileRole.value=p.role||'worker';profileLocation.value=p.location||'';profileAvatar.value=p.avatar_url||'';profileBio.value=p.bio||'';profileSkills.value=Array.isArray(p.skills)?p.skills.join(', '):(p.skills||'');updateProfilePreview();[profileName,profileUsername,profileRole,profileLocation,profileAvatar,profileBio,profileSkills].forEach(el=>el.addEventListener('input',updateProfilePreview));profileForm.addEventListener('submit',saveProfile)}
function updateProfilePreview(){const name=profileName?.value.trim()||'Your name',avatar=profileAvatar?.value.trim(),skills=(profileSkills?.value||'').split(',').map(x=>x.trim()).filter(Boolean);const preview=document.getElementById('profileLivePreview'),av=document.getElementById('profileAvatarPreview');if(av)av.innerHTML=avatar?`<img src="${esc(avatar)}" alt="Profile preview" onerror="this.remove()">`:esc(initials(name));if(preview)preview.innerHTML=`<div class="mini-profile"><div class="mini-avatar">${avatar?`<img src="${esc(avatar)}" alt="">`:esc(initials(name))}</div><div><strong>${esc(name)}</strong><small>@${esc(profileUsername?.value.trim()||'username')} · ${esc(profileRole?.value==='client'?'Client':'Worker')}</small><p>${esc(profileBio?.value.trim()||'Your bio will appear here.')}</p><div class="skills">${skills.slice(0,6).map(s=>`<span>${esc(s)}</span>`).join('')}</div></div></div>`}
async function saveProfile(e){e.preventDefault();const b=e.submitter;setAuthError('profileError','');setLoading(b,true,'Save changes');const payload={full_name:profileName.value.trim(),username:profileUsername.value.trim()||null,role:profileRole.value,location:profileLocation.value.trim()||null,avatar_url:profileAvatar.value.trim()||null,bio:profileBio.value.trim(),skills:profileSkills.value.split(',').map(x=>x.trim()).filter(Boolean)};const {data,error}=await supabaseClient.from('profiles').update(payload).eq('id',currentUser.id).select().single();if(error){setAuthError('profileError',error.message)}else{currentProfile=data;updateNav();closeModal();showToast('Profile updated ✓')}setLoading(b,false,'Save changes')}
async function handleTask(e){e.preventDefault();if(!currentUser){closeModal();openModal('login');showToast('Please log in first.');return}if(currentProfile?.role!=='client'){showToast('Switch your profile to Client to post tasks.');return}const b=e.submitter;setLoading(b,true,'Post task');const payload={client_id:currentUser.id,title:taskTitle.value.trim(),work_type:taskType.value,budget:Number(taskBudget.value),description:taskDescription.value.trim(),status:'open'};const {error}=await supabaseClient.from('tasks').insert(payload);if(error)setAuthError('taskError',error.message);else{closeModal();showToast('Task posted ✓')}setLoading(b,false,'Post task')}
async function loadTasks(){const list=document.getElementById('taskList');if(!list)return;const {data,error}=await supabaseClient.from('tasks').select('id,title,description,work_type,budget,status,created_at,client_id').eq('status','open').order('created_at',{ascending:false});if(error){list.innerHTML=`<div class="empty-state">Could not load tasks.<br><small>${esc(error.message)}</small></div>`;return}window.occTasks=data||[];renderTasks()}
function renderTasks(){const list=document.getElementById('taskList');if(!list)return;const q=(document.getElementById('taskSearch')?.value||'').toLowerCase();const f=document.getElementById('taskFilter')?.value||'all';const rows=(window.occTasks||[]).filter(t=>(f==='all'||t.work_type===f)&&(`${t.title} ${t.description}`.toLowerCase().includes(q)));if(!rows.length){list.innerHTML='<div class="empty-state"><div>✨</div><strong>No matching tasks yet</strong><p>Try another search or check back later.</p></div>';return}list.innerHTML=rows.map(t=>`<article class="task-card"><div class="task-card-top"><span class="pill">${esc(t.work_type)}</span><strong>₱${Number(t.budget).toLocaleString()}</strong></div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><div class="task-card-foot"><span>${new Date(t.created_at).toLocaleDateString()}</span><button class="btn small-btn" onclick="showToast('Application flow coming next — task saved in your marketplace.')">I'm interested</button></div></article>`).join('');document.getElementById('taskSearch')?.addEventListener('input',renderTasks);document.getElementById('taskFilter')?.addEventListener('change',renderTasks)}
async function renderAccountData(){const el=document.getElementById('accountData');await refreshAuth();const p=currentProfile||{};const mine=await supabaseClient.from('tasks').select('id,title,budget,status').eq('client_id',currentUser.id).order('created_at',{ascending:false}).limit(5);el.innerHTML=`<div class="account-profile"><div class="profile-avatar-lg">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(initials(p.full_name))}</div><div><div class="auth-kicker">YOUR ACCOUNT</div><h2>${esc(p.full_name||'OccuPick user')}</h2><p>${esc(currentUser.email||'')}</p><div class="account-tags"><span>${p.role==='client'?'Client':'Worker'}</span>${p.location?`<span>📍 ${esc(p.location)}</span>`:''}</div></div></div><div class="account-actions"><button class="btn" onclick="openModal('profile')">Customize profile</button>${p.role==='client'?'<button class="btn outline" onclick="openModal(\'task\')">Post a task</button>':'<button class="btn outline" onclick="openModal(\'marketplace\')">Find work</button>'}<button class="btn ghost" onclick="signOut()">Log out</button></div>${p.role==='client'?`<div class="account-section"><h3>Recent tasks</h3>${(mine.data||[]).map(t=>`<div class="account-task"><span>${esc(t.title)}</span><strong>₱${Number(t.budget).toLocaleString()}</strong><small>${esc(t.status)}</small></div>`).join('')||'<p>No tasks posted yet.</p>'}</div>`:''}`}
function updateNav(){const nav=document.getElementById('navActions');if(!nav)return;nav.innerHTML=currentUser?`<button class="btn ghost" onclick="openModal('profile')">Profile</button><button class="btn" onclick="openModal('account')">${esc(currentProfile?.full_name?.split(' ')[0]||'Account')}</button>`:`<button class="btn ghost" onclick="openModal('login')">Log in</button><button class="btn" onclick="openModal('signup')">Get started</button>`}
supabaseClient.auth.onAuthStateChange(async(_event,session)=>{currentUser=session?.user||null;if(currentUser){await ensureProfile(currentUser);const r=await supabaseClient.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();currentProfile=r.data||null}else currentProfile=null;updateNav()});
refreshAuth();
// Tinder demo
const stack=document.getElementById('matchStack');let active=document.getElementById('activeCard'),startX=0,currentX=0,dragging=false;
function refreshActive(){active=stack?.querySelector('.active-card');if(!active)return;active.onpointerdown=startDrag}
function startDrag(e){dragging=true;startX=e.clientX;currentX=0;active.classList.add('dragging');active.setPointerCapture?.(e.pointerId);active.onpointermove=dragMove;active.onpointerup=dragEnd;active.onpointercancel=dragEnd}
function dragMove(e){if(!dragging)return;currentX=e.clientX-startX;active.style.transform=`translateX(${currentX}px) rotate(${currentX*.08}deg)`;active.classList.toggle('like-hint',currentX>55);active.classList.toggle('pass-hint',currentX<-55)}
function dragEnd(){if(!dragging)return;dragging=false;active.classList.remove('dragging');active.onpointermove=null;active.onpointerup=null;if(Math.abs(currentX)>110)swipeCard(currentX>0?'right':'left');else{active.style.transform='';active.classList.remove('like-hint','pass-hint')}}
function swipeCard(direction){if(!active)return;const old=active,liked=direction==='right';old.classList.remove('dragging','like-hint','pass-hint');old.classList.add(liked?'swiping-right':'swiping-left');if(liked)createBurst();else showToast('Passed — finding another match');setTimeout(()=>{old.remove();const backs=stack.querySelectorAll('.card-back');const next=backs[backs.length-1];if(next){next.classList.remove('card-back');next.classList.add('active-card');next.style.transform='';next.style.opacity='';next.style.filter='';refreshActive()}else stack.innerHTML='<div class="match-card" style="display:grid;place-items:center;text-align:center"><div><div class="avatar" style="margin:auto auto 15px">✓</div><h3>All caught up!</h3><p>Check back soon for new opportunities.</p></div></div>'},420)}
function createBurst(){const burst=document.createElement('div');burst.className='match-burst';burst.innerHTML='<div class="bubble">It’s a match! 🎉</div>';stack.appendChild(burst);for(let i=0;i<16;i++){const s=document.createElement('i');s.className='spark';s.style.setProperty('--x',`${Math.cos(i/16*Math.PI*2)*150}px`);s.style.setProperty('--y',`${Math.sin(i/16*Math.PI*2)*150}px`);burst.appendChild(s)}showToast('It’s a match! 🎉');setTimeout(()=>burst.remove(),850)}
refreshActive();
